name: mercury_front
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: ^3.8.1

dependencies:
  dotenv: ^4.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.9
  flutter_local_notifications: ^19.3.1
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

# 웹 플랫폼 지원 명시
flutter_web:
  enabled: true