// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhhpyXcziZD1A0CPaPB6iJu7zgmuxTk5c',
    appId: '1:702343125251:web:880b8069339aa28bab7136',
    messagingSenderId: '702343125251',
    projectId: 'katec-mercury-16772',
    authDomain: 'katec-mercury-16772.firebaseapp.com',
    storageBucket: 'katec-mercury-16772.firebasestorage.app',
    measurementId: 'G-5E58FYVXP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxDPmHN97E7C-CgF5U0xmIJdLBJo0x3LM',
    appId: '1:702343125251:android:f4077573cf33be96ab7136',
    messagingSenderId: '702343125251',
    projectId: 'katec-mercury-16772',
    storageBucket: 'katec-mercury-16772.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7hfCO-UI0eVeJVXldGy9q22nfrEq3GNs',
    appId: '1:702343125251:ios:c06fc99dc8d6f401ab7136',
    messagingSenderId: '702343125251',
    projectId: 'katec-mercury-16772',
    storageBucket: 'katec-mercury-16772.firebasestorage.app',
    iosBundleId: 'com.example.mercuryFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7hfCO-UI0eVeJVXldGy9q22nfrEq3GNs',
    appId: '1:702343125251:ios:c06fc99dc8d6f401ab7136',
    messagingSenderId: '702343125251',
    projectId: 'katec-mercury-16772',
    storageBucket: 'katec-mercury-16772.firebasestorage.app',
    iosBundleId: 'com.example.mercuryFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhhpyXcziZD1A0CPaPB6iJu7zgmuxTk5c',
    appId: '1:702343125251:web:f628d3fa9c7978b2ab7136',
    messagingSenderId: '702343125251',
    projectId: 'katec-mercury-16772',
    authDomain: 'katec-mercury-16772.firebaseapp.com',
    storageBucket: 'katec-mercury-16772.firebasestorage.app',
    measurementId: 'G-RCKDFNW9N2',
  );

}