// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIavx0fbCHdeMAIc2gL-K25a22bnss-KY',
    appId: '1:851175873846:web:ded5ceb8a208cff60fa797',
    messagingSenderId: '851175873846',
    projectId: 'katec-mercury-d8d3f',
    authDomain: 'katec-mercury-d8d3f.firebaseapp.com',
    storageBucket: 'katec-mercury-d8d3f.firebasestorage.app',
    measurementId: 'G-Q0043RCXH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrmlirU664QVTmfYFWowKOtO6plpuh2KA',
    appId: '1:851175873846:android:ff4a845b7e26fe4f0fa797',
    messagingSenderId: '851175873846',
    projectId: 'katec-mercury-d8d3f',
    storageBucket: 'katec-mercury-d8d3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQYlga377UivDcSsZm8smSKtiIrZLZpEw',
    appId: '1:851175873846:ios:8027d7a63e434c940fa797',
    messagingSenderId: '851175873846',
    projectId: 'katec-mercury-d8d3f',
    storageBucket: 'katec-mercury-d8d3f.firebasestorage.app',
    iosBundleId: 'com.example.mercuryFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQYlga377UivDcSsZm8smSKtiIrZLZpEw',
    appId: '1:851175873846:ios:8027d7a63e434c940fa797',
    messagingSenderId: '851175873846',
    projectId: 'katec-mercury-d8d3f',
    storageBucket: 'katec-mercury-d8d3f.firebasestorage.app',
    iosBundleId: 'com.example.mercuryFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIavx0fbCHdeMAIc2gL-K25a22bnss-KY',
    appId: '1:851175873846:web:7b76c9dd51668c730fa797',
    messagingSenderId: '851175873846',
    projectId: 'katec-mercury-d8d3f',
    authDomain: 'katec-mercury-d8d3f.firebaseapp.com',
    storageBucket: 'katec-mercury-d8d3f.firebasestorage.app',
    measurementId: 'G-F22XVEWVQF',
  );

}